/*
* AUTOGENERATED FILE 
* DO NOT MODIFY MANUALLY!!!
*/
extern "C"{
    const char DESCRIPTION[255]  __attribute__((section(".metadata_pool")))= 
        "****************"  // placeholder for beggining
        "20250712T120745"   // DateTime using ISO-8601 format
        " "                 // alignment
        "f8e647d0"          // STLIB commit
        "--------"          // ADJ commit
        "143d17cf"          // Board commit
        // the '=' is used for unparsing
        ;
}